/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vincentpli/cel-tekton/pkg/apis/variablestores/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVariableStores implements VariableStoreInterface
type FakeVariableStores struct {
	Fake *FakeVariablestoresV1alpha1
	ns   string
}

var variablestoresResource = schema.GroupVersionResource{Group: "variablestores.tekton.dev", Version: "v1alpha1", Resource: "variablestores"}

var variablestoresKind = schema.GroupVersionKind{Group: "variablestores.tekton.dev", Version: "v1alpha1", Kind: "VariableStore"}

// Get takes name of the variableStore, and returns the corresponding variableStore object, and an error if there is any.
func (c *FakeVariableStores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VariableStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(variablestoresResource, c.ns, name), &v1alpha1.VariableStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VariableStore), err
}

// List takes label and field selectors, and returns the list of VariableStores that match those selectors.
func (c *FakeVariableStores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VariableStoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(variablestoresResource, variablestoresKind, c.ns, opts), &v1alpha1.VariableStoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VariableStoreList{ListMeta: obj.(*v1alpha1.VariableStoreList).ListMeta}
	for _, item := range obj.(*v1alpha1.VariableStoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested variableStores.
func (c *FakeVariableStores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(variablestoresResource, c.ns, opts))

}

// Create takes the representation of a variableStore and creates it.  Returns the server's representation of the variableStore, and an error, if there is any.
func (c *FakeVariableStores) Create(ctx context.Context, variableStore *v1alpha1.VariableStore, opts v1.CreateOptions) (result *v1alpha1.VariableStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(variablestoresResource, c.ns, variableStore), &v1alpha1.VariableStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VariableStore), err
}

// Update takes the representation of a variableStore and updates it. Returns the server's representation of the variableStore, and an error, if there is any.
func (c *FakeVariableStores) Update(ctx context.Context, variableStore *v1alpha1.VariableStore, opts v1.UpdateOptions) (result *v1alpha1.VariableStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(variablestoresResource, c.ns, variableStore), &v1alpha1.VariableStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VariableStore), err
}

// Delete takes name of the variableStore and deletes it. Returns an error if one occurs.
func (c *FakeVariableStores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(variablestoresResource, c.ns, name), &v1alpha1.VariableStore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVariableStores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(variablestoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VariableStoreList{})
	return err
}

// Patch applies the patch and returns the patched variableStore.
func (c *FakeVariableStores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VariableStore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(variablestoresResource, c.ns, name, pt, data, subresources...), &v1alpha1.VariableStore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VariableStore), err
}
