apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: celrun-with-context-
spec:
  ref:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: VariableStore
    name: example
  params:
    - name: name
      value: "'hello' + context_one"
    - name: types
      value: "type(name)"
    - name: expression-use-context
      value: "name + ' is type of name and types' + types"
